SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM IMPORTED_BOOK;
SELECT * FROM ORDERS;
SELECT PRICE, BOOKID FROM BOOK;
SELECT NAME,address, PHONE FROM CUSTOMER;


-- 중복 없이 출력 DISTINCT
SELECT PUBLISHER FROM BOOK;
SELECT DISTINCT PUBLISHER FROM BOOK;           

--Q. 가격이 10,000이상인 도서를 검색
-- 조건 검색해서 SELECT는 "WHERE"
SELECT * FROM BOOK 
WHERE  PRICE > 20000;

-- 가격이 10000이상 20000이하인 도서를 검색하시오 (2가지 방법)
-- OPTION1
SELECT * FROM BOOK 
WHERE  PRICE >= 10000 AND PRICE <= 20000;
-- OPTION2
SELECT * FROM BOOK 
WHERE PRICE BETWEEN 10000 AND 20000;

-- LIKE는 정확히 '축구의 역사'와 일치하는 행만 선택: LIKE
SELECT BOOKNAME, PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '축구의 역사';

-- '축구'가 포함된 출판사: '%xx%'
SELECT BOOKNAME, PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '%축구%';

-- 도서이름의 왼쪽 두 번째 위치에 '구'라는 문자열을 갖는 도서: '_X%'
SELECT BOOKNAME ,PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '_구%';


-- 정렬 오름차순 ORDERED BY
SELECT * FROM BOOK
ORDER BY BOOKNAME;

-- 정렬 내림차순: DESC
SELECT * FROM BOOK
ORDER BY PRICE DESC;

-- Q. 도서를 가격순으로 검색하고, 가격이 같으면 이름순으로 검색
SELECT * FROM BOOK
ORDER BY PRICE, BOOKNAME;

-- Q. 2번 김연아 고객이 주문한 도서의 총 판매액을 구하시오
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
-- 조인이 필요해서 지금은 x

-- (STEP1) 일단 김연아의 COSTID가 2이므로
SELECT SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE CUSTID = 2;

-- (STEP2) GROUP BY: 데이터를 특정 기준에 따라 그룹화하는데 사용. 이를 통해 집계 함수 (SUM, AVG, MAX, MIN, COUNT)를 이용
SELECT SUM(SALEPRICE) AS TOTAL,
AVG(SALEPRICE) AS AVERAGE,
MAX(SALEPRICE) AS MAXIMUM,
MIN(SALEPRICE) AS MINIMUM
FROM ORDERS;


SELECT * FROM ORDERS;

-- 총 판매액을 CUSTID를 기준으로 그룹화
-- 아래 코드의 설명; ORDERS 테이블로 부터 COL을 (1)CUSTID, (2) COUNT(*), (3) SUM(SALEPRICE)로 검색하는데..
-- 이때 BOOKID가 5초과인 조건으로 CUSTID 기준으로 검색
SELECT CUSTID, COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5
GROUP BY CUSTID;
-- <== 여기서 GROUP BY CUSTID가 없으면 ERROR가 나오는데, 이건 CUSTID가 검색 컬럼에 포함되어 있으니 수행하기 불가능


-- CF) 그럼 CUSTID를 검색 COL에서 제거를 하고 "GROUP BY CUSTID"를 안하면 ERORR가 발생 안하나? ==> 에러 없음
SELECT COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5;

-- 도서 수량이 2보다 조건
SELECT CUSTID, COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5
GROUP BY CUSTID
HAVING COUNT(*) > 2;


-- TASK1.0517. 출판사가 "굿스포츠" 혹은 "대한 미디어"인 도서를 검색하시오 (3가지)
-- OPTION1
SELECT * FROM BOOK
WHERE PUBLISHER='굿스포츠' OR PUBLISHER='대한미디어';
-- OPTION2
SELECT * FROM BOOK
WHERE PUBLISHER LIKE '%스포츠%' OR PUBLISHER LIKE  '%대한%';
-- OPTION3
SELECT * FROM BOOK
WHERE PUBLISHER IN ('굿스포츠','대한미디어');
-- Option4
SELECT * FROM BOOK
WHERE PUBLISHER='굿스포츠' 
UNION
SELECT * FROM BOOK
WHERE PUBLISHER='대한미디어';

-- Task2_0517. 출판사가 '굿스포츠' 혹은 '대한미디어'가 아닌 도서를 검색
SELECT * FROM BOOK
WHERE PUBLISHER !='굿스포츠' AND PUBLISHER != '대한미디어';
SELECT * FROM BOOK
WHERE PUBLISHER NOT IN ('굿스포츠','대한미디어');

-- Task3_0517. 축구에 관한 도서 중 가격이 20,000원 이상인 도서를 검색하시오.
-- %: 0개 이상의 임의의 문자, _ 정확히 1개의 임의의 문자
SELECT * FROM BOOK
WHERE BOOKNAME LIKE '%축구%' AND PRICE >= 20000;

--Task4_0517. 2번 김연아 고객이 주문한 도서의 총 판매액을 구하시오.
SELECT CUSTOMER.NAME, ORDERS.CUSTID, SUM(ORDERS.SALEPRICE) AS "총 판매액"
FROM ORDERS
JOIN CUSTOMER ON CUSTOMER.CUSTID = ORDERS.CUSTID
WHERE CUSTOMER.NAME = '김연아'
GROUP BY CUSTOMER.NAME,ORDERS.CUSTID;

-- 강사님
SELECT  ORDERS.CUSTID, CUSTOMER.NAME, SUM(ORDERS.SALEPRICE) AS "총 판매액"
FROM ORDERS, CUSTOMER
WHERE CUSTOMER.CUSTID=2 AND ORDERS.CUSTID = CUSTOMER.CUSTID
GROUP BY CUSTOMER.NAME,ORDERS.CUSTID;

SELECT  CUSTOMER.NAME, ORDERS.CUSTID, SUM(ORDERS.SALEPRICE) AS "총 판매액"
FROM ORDERS
INNER JOIN CUSTOMER ON ORDERS.CUSTID = CUSTOMER.CUSTID
WHERE CUSTOMER.CUSTID=2
GROUP BY CUSTOMER.NAME,ORDERS.CUSTID;

--CF Task4_0517. 2번 김연아 고객이 주문한 도서의 총 갯수와 총 판매액을 구하시오.
SELECT  CUSTOMER.NAME, ORDERS.CUSTID, SUM(ORDERS.SALEPRICE) AS "총 판매액", COUNT(ORDERS.ORDERID) AS "총 도서 구매 수"
FROM ORDERS
INNER JOIN CUSTOMER ON ORDERS.CUSTID = CUSTOMER.CUSTID
WHERE CUSTOMER.CUSTID=2
GROUP BY CUSTOMER.NAME,ORDERS.CUSTID;

--Task5_0517. 가격이 8,000원 이상인 도서를 구매한 고객에 대하여 고객별 주문 도서의 총 수량을 구하시오. 
--단, 두 권 이상 구매한 고객만 구하시오.
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
SELECT * FROM BOOK;

SELECT CUSTOMER.NAME,CUSTOMER.CUSTID, COUNT(*) AS 도서수량
FROM CUSTOMER
JOIN ORDERS ON 
CUSTOMER.CUSTID = ORDERS.CUSTID
WHERE ORDERS.SALEPRICE >= 8000
GROUP BY CUSTOMER.CUSTID, CUSTOMER.NAME
HAVING COUNT(*) >= 2
ORDER BY CUSTOMER.CUSTID;

-- 강사님
SELECT CUSTID, COUNT(*) AS "도서수량"
FROM ORDERS
WHERE SALEPRICE >= 8000
GROUP BY CUSTID
HAVING COUNT(*) >=2;


-- 보선씨 TIP
SELECT B.CUSTID, COUNT(*)
FROM BOOK A,ORDERS B
WHERE
A.BOOKID = B.BOOKID
AND A.PRICE >= 8000
GROUP BY B.CUSTID
HAVING COUNT(*) >= 2;

--Task6_0517. 고객의 이름과 고객이 주문한 도서의 판매가격을 검색하시오.
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
SELECT * FROM BOOK;

SELECT CUSTOMER.NAME, ORDERS.SALEPRICE, ORDERS.BOOKID
FROM CUSTOMER
JOIN ORDERS ON 
CUSTOMER.CUSTID = ORDERS.CUSTID
ORDER BY NAME, SALEPRICE;

--Task7_0517. 고객별로 주문한 모든 도서의 총 판매액을 구하고, 고객별로 정렬하시오.
SELECT CUSTOMER.NAME, SUM(ORDERS.SALEPRICE) AS "총액"
FROM CUSTOMER
JOIN ORDERS ON 
CUSTOMER.CUSTID = ORDERS.CUSTID
GROUP BY NAME
ORDER BY "총액";

-- 강사님
SELECT CUSTID, SUM(SALEPRICE) AS  "총판매액"
FROM ORDERS
GROUP BY CUSTID
ORDER BY "총판매액";

SELECT NAME, SUM(SALEPRICE) AS "총판매액"
FROM ORDERS O, CUSTOMER C
WHERE C.CUSTID=O.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

-- 5/20 (월)
-- Q. 고객의 이름과 고객이 주문한 도서의 이름을 구하시오
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
SELECT * FROM BOOK;

SELECT C.NAME, B.BOOKNAME
FROM CUSTOMER C, 
ORDERS O, 
BOOK B
WHERE C.CUSTID = O.CUSTID
AND O.BOOKID = B.BOOKID
ORDER BY C.NAME;

SELECT C.NAME, B.BOOKNAME
FROM CUSTOMER C 
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
ORDER BY C.NAME;

-- Q. 가격이 20000원인 도서를 주문한 고객의 이름과 도서의 이름을 구하시오
SELECT C.NAME, B.BOOKNAME, O.SALEPRICE
FROM CUSTOMER C 
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID;

SELECT C.NAME, B.BOOKNAME, O.SALEPRICE
FROM CUSTOMER C 
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE O.SALEPRICE = 20000;

SELECT C.NAME, SUM(O.SALEPRICE) AS "총구매액"
FROM CUSTOMER C 
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE O.SALEPRICE > 4000
GROUP BY C.NAME;

--JOIN은 두 개 이상의 테이블을 연결하여 관련된 데이터를 결합할 때 사용
--내부 조인 (Inner Join)
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER
INNER JOIN ORDERS ON CUSTOMER.CUSTID=ORDERS.CUSTID;

--왼쪽 외부 조인 (Left Outer Join) : . 두 번째 테이블에 일치하는 데이터가 없는 경우 NULL 값이 사용
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER
LEFT OUTER JOIN ORDERS ON CUSTOMER.CUSTID=ORDERS.CUSTID;

--오른쪽 외부 조인 (Right Outer Join) : 첫 번째 테이블에 일치하는 데이터가 없는 경우 NULL 값이 사용
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER
RIGHT OUTER JOIN ORDERS ON CUSTOMER.CUSTID=ORDERS.CUSTID;

--FULL OUTER JOIN : 일치하는 데이터가 없는 경우 해당 테이블에서는 NULL 값이 사용
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER
FULL OUTER JOIN ORDERS ON CUSTOMER.CUSTID=ORDERS.CUSTID;

--CROSS JOIN : 두 테이블 간의 모든 가능한 조합을 생성
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER
CROSS JOIN ORDERS;

-- Q. 도서를 구매하지; 않은 고객을 포함하여 고객의 이름과 고객이 주문한 도서의 판매가격을 구하시오 (2가지 방법, WHERE, JOIN)
-- OPTION 1 USING WHERE
SELECT C.NAME,B.BOOKNAME, O.SALEPRICE
FROM CUSTOMER C, BOOK B, ORDERS O
WHERE C.CUSTID=O.CUSTID(+)
AND B.BOOKID(+) = O.BOOKID
ORDER BY C.NAME;

-- OPTION 2 USING JOIN
SELECT C.NAME, B.BOOKNAME, O.SALEPRICE
FROM CUSTOMER C
LEFT OUTER JOIN ORDERS O ON C.CUSTID=O.CUSTID
LEFT OUTER JOIN BOOK B ON B.BOOKID=O.BOOKID
ORDER BY C.NAME;

-- 부속 질의 (SUB QUERY)
-- Q. 도서를 구매한 적이 있는 고객의 이름을 검색하시오
SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID FROM ORDERS);

-- Q. 대한 미디어에서 출판한 도서를 구매한 고객의 이름을 보이시오
SELECT CUSTOMER.NAME
FROM CUSTOMER
WHERE CUSTID IN (
SELECT ORDERS.CUSTID 
FROM ORDERS 
INNER JOIN BOOK 
ON BOOK.BOOKID=ORDERS.BOOKID 
WHERE BOOK.PUBLISHER='대한미디어');

-- 강사님
SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID FROM ORDERS
WHERE BOOKID IN (SELECT BOOKID FROM BOOK
WHERE PUBLISHER ='대한미디어'));

--Q. 출판사별로 출판사의 평균 도서 가격보다 비싼 도서를 구하시오.
SELECT B1.BOOKNAME 
FROM BOOK B1 
WHERE B1.PRICE > (SELECT AVG(B2.PRICE) 
FROM BOOK B2 
WHERE B2.PUBLISHER = B1.PUBLISHER);

--Q. 도서를 주문하지 않은 고객의 이름을 보이시오.
SELECT C.NAME
FROM CUSTOMER C
WHERE C.CUSTID NOT IN (
SELECT ORDERS.CUSTID FROM ORDERS);

--강사님
SELECT NAME
FROM CUSTOMER
WHERE CUSTID NOT IN (
SELECT CUSTID FROM ORDERS);

--Q. 주문이 있는 고객의 이름과 주소를 보이시오.
SELECT NAME 고객이름, ADDRESS 고객주소
FROM CUSTOMER 
WHERE CUSTID IN (
SELECT CUSTID FROM ORDERS);

SELECT NAME "고객 이름", ADDRESS "고객 주소"
FROM CUSTOMER 
WHERE CUSTID IN (
SELECT CUSTID FROM ORDERS);


-- Re-Try
--Q. ‘대한미디어’에서 출판한 도서를 구매한 고객의 이름을 보이시오.
SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN ( SELECT CUSTID FROM ORDERS
WHERE BOOKID IN ( SELECT BOOKID FROM BOOK
WHERE PUBLISHER = '대한미디어'));

--Q. 출판사별로 출판사의 평균 도서 가격보다 비싼 도서를 구하시오.
SELECT BOOKNAME
FROM BOOK
WHERE PRICE > (
SELECT PUBLISHER, AVG(PRICE) 
FROM BOOK
GROUP BY PUBLISHER;

--Q. 도서를 주문하지 않은 고객의 이름을 보이시오.

--Q. 주문이 있는 고객의 이름과 주소를 보이시오.



-- 데이터 타입
-- 숫자형 (Numeric Types)
-- NUMBER: 가장 범용적인 숫자 데이터 타입. 정수, 실수, 고정 소수점, 부동 소수점 수를 저장
-- NUMBER는 NUMBER(38,0)와 같은 의미로 해석; PRECISION 38은 자리수 , SCALE 0는 소수점 이하 자리수: 0
-- NUMBER(10): 자리수가 10 소수점 0, NUMBER(8,2): 자리수 2, 소수점 2==> 8에는 소수점 이하 2도 포함됨.
--문자형 (Character Types)
--VARCHAR2(size): 가변 길이 문자열을 저장. size는 최대 문자 길이를 바이트 혹은 글자수로 지정
--NVARCHAR2(size)의 사이즈를 지정할 때는 바이트 단위 대신 항상 문자 단위로 크기가 지정
--CHAR(size): 고정 길이 문자열을 저장. 지정된 길이보다 짧은 문자열이 입력되면 나머지는 공백으로 채워짐
--날짜 및 시간형 (Date and Time Types)
--DATE: 날짜와 시간을 저장. 데이터 타입은 년, 월, 일, 시, 분, 초를 포함
--DATE 타입은 날짜와 시간을 YYYY-MM-DD HH24:MI:SS 형식으로 저장합니다.
--예를 들어, 2024년 5월 20일 오후 3시 45분 30초는 2024-05-20 15:45:30으로 저장

--TIMESTAMP: 날짜와 시간을 더 상세히 나노초 단위까지 저장
--이진 데이터형 (Binary Data Types)
--BLOB: 대량의 이진 데이터를 저장. 이미지, 오디오 파일 등을 저장하는 데 적합
--대규모 객체형 (Large Object Types)
--CLOB: 대량의 문자 데이터를 저장
--NCLOB: 대량의 국가별 문자 집합 데이터를 저장

--문자 인코딩의 의미
--컴퓨터는 숫자로 이루어진 데이터를 처리. 인코딩을 통해 문자(예: 'A', '가', '?')를 
--숫자(코드 포인트)로 변환하여 컴퓨터가 이해하고 저장할 수 있게 한다.
--예를 들어, ASCII 인코딩에서는 대문자 'A'를 65로, 소문자 'a'를 97로 인코딩. 
--유니코드 인코딩에서는 'A'를 U+0041, 한글 '가'를 U+AC00, 이모티콘 '?'를 U+1F60A로 인코딩
--아스키는 7비트를 사용하여 총 128개의 문자를 표현하는 반면 유니코드는 최대 1,114,112개의 문자를 표현

--ASCII 인코딩:
--문자 'A' -> 65 (10진수) -> 01000001 (2진수)
--문자 'B' -> 66 (10진수) -> 01000010 (2진수)

--유니코드(UTF-8) 인코딩: 
--문자 'A' -> U+0041 -> 41 (16진수) -> 01000001 (2진수, ASCII와 동일)
--문자 '가' -> U+AC00 -> EC 95 80 (16진수) -> 11101100 10010101 10000000 (2진수)

--CLOB: CLOB은 일반적으로 데이터베이스의 기본 문자 집합(예: ASCII, LATIN1 등)을 사용하여 텍스트 데이터를 저장. 
--이 때문에 주로 영어와 같은 단일 바이트 문자로 이루어진 텍스트를 저장하는 데 사용.
--NCLOB: NCLOB은 유니코드(UTF-16)를 사용하여 텍스트 데이터를 저장. 따라서 다국어 지원이 필요할 때, \
--즉 다양한 언어로 구성된 텍스트 데이터를 저장할 때 적합. 다국어 문자가 포함된 데이터를 효율적으로 처리할 수 있다.

--제약조건 :  
--DEFAULT : 열에 명시적인 값이 제공되지 않을 경우 사용될 기본값을 지정


----------------------------------------------------------------------------------------
-- VARCHAR2는 두 가지 방식으로 길이를 정의: 바이트와 문자
-- 설정 확인 방법
SELECT *
FROM V$NLS_PARAMETERS
WHERE PARAMETER = 'NLS_LENGTH_SEMANTICS';
-- NLS_LENGTH_SEMANTICS는 바이트(Byte) 또는 문자(Char)길이를 사용하여 char, varchar2 타입의 컬럼을 만들수 있습니다. 
이때 기존의 컬럼은 영향을 받지 않습니다.
-- ALTER [SYSTEM|SESSION] SET NLS_LENGTH_SEMANTICS=[CHAR|BYTE]


--AUTHOR 테이블 생성
CREATE TABLE AUTHORS(
ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
NATIONALITY VARCHAR2(50)
);

INSERT INTO AUTHORS VALUES(1,'HWANWOOK','CHOI','ROK');
INSERT INTO AUTHORS VALUES(2,'YONWOO','CHOI','');

SELECT * FROM AUTHORS;
DROP TABLE AUTHORS;

-- Q. NEWBOOK이라는 테이블을 생성하세요
CREATE TABLE NEWBOOK (
    BOOKID NUMBER,
    ISBN NUMBER(13),
    BOOKNAME VARCHAR2(50) NOT NULL,
    AUTHOR VARCHAR2(50) NOT NULL,
    PUBLISHER VARCHAR2(30) NOT NULL,
    PRICE NUMBER DEFAULT 10000 CHECK(PRICE>10000),
    PUBLISHED_DATE DATE,
    PRIMARY KEY(BOOKID)
);

INSERT INTO NEWBOOK VALUES (1, 9781234567890, 'SQL Guide', 'John Doe', 'TechBooks', 15000, TO_DATE('2024-05-20', 'YYYY-MM-DD'));

-- 아래와 같이 동일하게 넣으면 BOOKID가 PRIMARY로 DEFINE되어 있으므로 중복 x ==> 에러
INSERT INTO NEWBOOK VALUES (1, 9781234567890, 'SQL Guide', 'John Doe', 'TechBooks', 15000, TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO NEWBOOK VALUES (2, 9781234567890, 'SQL Guide', 'John Doe', 'TechBooks', 15000, TO_DATE('2024-05-20 15:45:30', 'YYYY-MM-DD HH24:MI:SS'));

--ISBN의 자리수가 13을 넘어가므로 에러
INSERT INTO NEWBOOK VALUES (3, 97812345678909342, 'SQL Guide', 'John Doe', 'TechBooks', 15000, TO_DATE('2024-05-20 15:45:30', 'YYYY-MM-DD HH24:MI:SS'));

DELETE FROM  NEWBOOK;
ALTER TABLE NEWBOOK MODIFY (ISBN VARCHAR2(50));
SELECT * FROM NEWBOOK;

SELECT * FROM NEWBOOK;
    
DROP TABLE NEWBOOK;

CREATE TABLE NEWBOOK (
    BOOKID NUMBER,
    ISBN NUMBER(13),
    BOOKNAME VARCHAR2(50) NOT NULL,
    AUTHOR VARCHAR2(50) NOT NULL,
    PUBLISHER VARCHAR2(50) NOT NULL,
    PRICE NUMBER DEFAULT 10000 CHECK(PRICE >10000),
    PUBLISHED_DATE DATE,
    PRIMARY KEY(BOOKID)
);

INSERT INTO NEWBOOK VALUES (1, '12345567909', 'BOOKNAME1', 'JANE DOE', 
'PRENTICEHALL',15000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:Mi:SS'));
INSERT INTO NEWBOOK VALUES (2, '1245567909', 'BOOKNAME2', 'JOHN DOE', 
'ELSVIER',25000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:Mi:SS'));
SELECT * FROM NEWBOOK;
ALTER TABLE NEWBOOK MODIFY (ISBN NUMBER(20));
DESC NEWBOOK;

INSERT INTO NEWBOOK VALUES (3, 124534345909, 'BOOKNAME3', 'HUGH GRANT', 
'FERGAMON',35000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));

-- 형태를 볼려면.. DESCRIPTION
DESC NEWBOOK;

ALTER TABLE NEWBOOK MODIFY (ISBN VARCHAR2(10));
ALTER TABLE NEWBOOK ADD AUTHOR_ID NUMBER;
ALTER TABLE NEWBOOK DROP COLUMN AUTHOR_ID;

SELECT * FROM NEWBOOK;


---------------------------------------------------------------------------
-- ON DELETE CASCADE 옵션이 설정되어 있어, NEWCUSTOMER 테이블에서 어떤 고객의 레코드가 삭제되면, 해당 고객의 모둔 주문이 NEWORDERS 테이블에서도 자동으로 삭제

CREATE TABLE NEWCUSTOMER(
CUSTID NUMBER PRIMARY KEY,
NAME VARCHAR2(40),
ADDRESS VARCHAR2(40),
PHONE VARCHAR2(30));

CREATE TABLE NEWORDERS(
ORDERID NUMBER,
CUSTID NUMBER NOT NULL,
BOOKID NUMBER NOT NULL,
SALEPRICE NUMBER,
ORDERDATE DATE,
PRIMARY KEY(ORDERID),
FOREIGN KEY(CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE);
DESC NEWORDERS;

SELECT * FROM NEWCUSTOMER;
SELECT * FROM NEWORDERS;

-- Q. 10개의 속성으로 구성되는 테이블 2개를 작성하세요, 단 FOREIGN KEY를 적용하여 한쪽 TABLE의 데이터를 삭제 시 다른 테이블의 관련된
-- 데이터도 모두 삭제되도록 하세요. (모든 제약 조건을 사용)
-- 단, 각 테이블에 5개의 데이터를 입력하고 두번째 테이블에 첫번째 데이터를 참조하고 있는 속성을 선택하여 데이터 삭제

--------------------------------------------------------------------------------
CREATE TABLE NEWCUSTOMER(
CUSTID NUMBER PRIMARY KEY,
NAME VARCHAR2(40),
ADDRESS VARCHAR2(40),
PHONE VARCHAR2(30));
INSERT INTO NEWCUSTOMER VALUES (1, 'JOHN DOE', 'APT-1', '000-000-0001');
INSERT INTO NEWCUSTOMER VALUES (2, 'JANE DOE', 'APT-2', '000-000-0002');
INSERT INTO NEWCUSTOMER VALUES (3, 'HUGH GRANT', 'APT-3', '000-000-0003');
INSERT INTO NEWCUSTOMER VALUES (4, 'JULIA ROBERTS', 'APT-4', '000-000-0004');
INSERT INTO NEWCUSTOMER VALUES (5, 'NICOLE KIDMAN', 'APT-5', '000-000-0005');

CREATE TABLE NEWORDERS (
ORDERID NUMBER,
CUSTID NUMBER NOT NULL,
BOOKID NUMBER NOT NULL,
SALEPRICE NUMBER,
ORDERDATE DATE,
PRIMARY KEY(ORDERID),
FOREIGN KEY(CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE);

INSERT INTO NEWORDERS VALUES (1,1,1,14000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (2,1,3,24000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (3,2,2,24000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (4,3,4,32000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (5,1,6,3000, SYSDATE);

SELECT * FROM NEWORDERS;
SELECT * FROM NEWCUSTOMER;
DROP TABLE NEWORDERS;
DROP TABLE NEWCUSTOMER;

-- NEWCUSTOMER에서 PRIMARY KEY인 CUSTID=1인 DATA를 삭제를 하면 NEWORDERS에서 CUSTID=1에 해당하는 ORDERS DATA도 모두 삭제..
DELETE FROM NEWCUSTOMER WHERE CUSTID=1;

-- NEWORDERS에서 CUSTID=3인 DATA를 삭제 하면 NEWORDERS에서는 삭제되지만, NEWCUSTOMER에서 CUSTID=3인 DATA들은 삭제 x.. 그대로 존재..
DELETE FROM NEWORDERS WHERE CUSTID=3;
DELETE FROM NEWORDERS WHERE CUSTID=1;

-- NEWORDERS에서 CUSTID 컬럼을 삭제하더라도 NEWCUSTOMER에서는 삭제 안되고 그대로 남아 있음
ALTER TABLE NEWORDERS DROP COLUMN CUSTID;

-- 반면, NEWCUSTOMER에서는 CUSTID 컬럼은 NEWORDERS에서 FOREIGN 키로 설정되어 있어서 아예 삭제가 안됨
-- 다만, NEWORDERS에서 FOREIGN 키로 설정되어 있던  CUSTID를 먼저 DROP시키고 나서 NEWCOSTOMER에서 CUSTID COLUMN을 DROP으로 삭제는 가능
ALTER TABLE NEWCUSTOMER DROP COLUMN CUSTID;

----------------------------------------------------------------------------------------------------------
--  연습
SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

--Q. ‘대한미디어’에서 출판한 도서를 구매한 고객의 이름을 보이시오.
SELECT NAME FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID FROM ORDERS
WHERE BOOKID IN (SELECT BOOKID FROM BOOK
WHERE PUBLISHER = '대한미디어'));


-- Q. 가장 비싼 책의 정보를 검색 
SELECT BOOKNAME, PRICE, PUBLISHER FROM BOOK 
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOK);

--Q. 출판사별로 출판사의 평균 도서 가격보다 비싼 도서를 구하시오.
SELECT B1.PUBLISHER, B1.BOOKNAME, B1.PRICE 
FROM BOOK B1
WHERE B1.PRICE > (SELECT AVG(B2.PRICE)
FROM BOOK B2
WHERE B2.PUBLISHER = B1.PUBLISHER);
--GROUP BY PUBLISHER ==> 필요 없어 각각이 도서에 대해서 평균 보다 비싼 개별 도서 이므로 

--Q. 도서를 주문하지 않은 고객의 이름을 보이시오.
SELECT NAME FROM CUSTOMER
WHERE CUSTID NOT IN (
SELECT CUSTID FROM ORDERS);

SELECT NAME FROM CUSTOMER
WHERE CUSTID IN (
SELECT CUSTID FROM ORDERS);

--Q. 주문이 있는 고객의 이름과 주소를 보이시오.
SELECT NAME, ADDRESS FROM CUSTOMER
WHERE CUSTID IN (
SELECT CUSTID FROM ORDERS);



-- TASK1_0520. 10개의 속성으로 구성되는 테이블 2개를 작성하세요, 단 FOREIGN KEY를 적용하여 한쪽 TABLE의 데이터를 삭제 시 다른 테이블의 관련된
-- 데이터도 모두 삭제되도록 하세요. (모든 제약 조건을 사용)
-- 단, 각 테이블에 5개의 데이터를 입력하고 두번째 테이블에 첫번째 테이블의 데이터를 참조하고 있는 속성을 선택하여 데이터 삭제
CREATE TABLE NEWCUSTOMER(
CUSTID NUMBER PRIMARY KEY,
NAME VARCHAR2(40),
ADDRESS VARCHAR2(40),
PHONE VARCHAR2(30));
INSERT INTO NEWCUSTOMER VALUES (1, 'JOHN DOE', 'APT-1', '000-000-0001');
INSERT INTO NEWCUSTOMER VALUES (2, 'JANE DOE', 'APT-2', '000-000-0002');
INSERT INTO NEWCUSTOMER VALUES (3, 'HUGH GRANT', 'APT-3', '000-000-0003');
INSERT INTO NEWCUSTOMER VALUES (4, 'JULIA ROBERTS', 'APT-4', '000-000-0004');
INSERT INTO NEWCUSTOMER VALUES (5, 'NICOLE KIDMAN', 'APT-5', '000-000-0005');

CREATE TABLE NEWORDERS (
ORDERID NUMBER,
CUSTID NUMBER NOT NULL,
BOOKID NUMBER NOT NULL,
SALEPRICE NUMBER,
ORDERDATE DATE,
PRIMARY KEY(ORDERID),
FOREIGN KEY(CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE);

INSERT INTO NEWORDERS VALUES (1,1,1,14000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (2,1,3,24000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (3,2,2,24000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (4,3,4,32000, TO_DATE('2024-05-20 14:49:30','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO NEWORDERS VALUES (5,1,6,3000, SYSDATE);
------------------------------------------------------------------------------------------------
-- NEWORDERS의 'CUSTID' KEY는 NEWCUSTOMER의 PRIMARY KEY인 'CUSTID'를 REFERENCING해서 FOREIGN KEY로 설정해 둠.
SELECT * FROM NEWORDERS;
SELECT * FROM NEWCUSTOMER;
DROP TABLE NEWORDERS;
DROP TABLE NEWCUSTOMER;

-- NEWCUSTOMER에서 PRIMARY KEY인 CUSTID=1인 DATA를 삭제를 하면 NEWORDERS에서 CUSTID=1에 해당하는 ORDERS DATA도 모두 삭제..
DELETE FROM NEWCUSTOMER WHERE CUSTID=1;

-- NEWORDERS에서 CUSTID=3인 DATA를 삭제 하면 NEWORDERS에서는 삭제되지만, NEWCUSTOMER에서 CUSTID=3인 DATA들은 삭제 x.. 그대로 존재..
DELETE FROM NEWORDERS WHERE CUSTID=3;
DELETE FROM NEWORDERS WHERE CUSTID=1;

-- NEWORDERS에서 CUSTID 컬럼을 삭제하더라도 NEWCUSTOMER에서는 삭제 안되고 그대로 남아 있음
ALTER TABLE NEWORDERS DROP COLUMN CUSTID;

-- 반면, NEWCUSTOMER에서는 CUSTID 컬럼은 NEWORDERS에서 FOREIGN 키로 설정되어 있어서 아예 삭제가 안됨
-- 다만, NEWORDERS에서 FOREIGN 키로 설정되어 있던  CUSTID를 먼저 DROP시키고 나서 NEWCOSTOMER에서 CUSTID COLUMN을 DROP으로 삭제는 가능
ALTER TABLE NEWCUSTOMER DROP COLUMN CUSTID;

DROP TABLE NEWORDERS;
DROP TABLE NEWCUSTOMER;


---------------------------- 강사님 Task1_0520. 10개의 속성으로 구성되는 테이블 2개를 작성하세요. 단 FOREIGN KEY를 적용하여 한쪽 테이블의 데이터를 삭제 시 
-- 다른 테이블의 관련되는 데이터도 모두 삭제되도록 하세요. (모든 제약조건을 사용)
-- 단, 각 테이블에 5개의 데이터를 입력하고 두번째 테이블에 첫번째 데이터를 참조하고 있는 속성을 선택하여 데이터 삭제 

DROP table mart;
DROP table department;
create table mart(
    custid number primary key
    , name varchar2(20)
    , age number
    , sx varchar2(20)
    , phone number not null
    , address varchar2(100)
    , frequency number -- 방문 빈도
    , amount_num number
    , amount_price number
    , parking varchar2(20) -- 주차여부
    , family number -- 가족 구성원 수
);

alter table mart drop column amount_num;
alter table mart modify (name varchar2(30));
alter table mart modify (phone varchar2(20));

DESC mart;
insert into mart values(1, '고길동', 32, '남', '010-1234-1234', '서울 강남', 5, 1500000, 'N', 3);
insert into mart values(2, '손흥민', 31, '남', '010-7777-1234', '강원 춘천', 5, 200000000, 'Y', 4);
insert into mart values(3, '이순신', 57, '남', '010-1592-1234', '경남 통영', 5, 270000, 'N', 1);
insert into mart values(4, '아이유', 30, '여', '010-0516-1234', '서울 서초', 5, 750000000, 'Y', 4);
insert into mart values(5, '임영웅', 30, '남', '010-0517-1235', '서울 역삼', 5, 75000000, 'Y', 2);

select * from mart;

create table department(
    custid number primary key
    , name varchar(20)
    , age number
    , sx varchar2(20)
    , phone number not null
    , address varchar2(100)
    , use_store varchar2(100) -- 자주 찾는 매장
    , amount_num number
    , amount_price number
    , valet varchar2(20) -- 발렛파킹 서비스 사용여부
    , rounge varchar2(20) -- vip 라운지 사용여부
    , foreign key (custid) references mart(custid) on delete cascade
);

alter table department modify (amount_price check (amount_price > 100000000));
alter table department modify (rounge default 'Y');
alter table department modify (valet default 'Y');
alter table department modify (phone varchar2(100));
alter table department drop column amount_num;
--alter table department add (custid number);
select * from department;

insert into department values(1, '손흥민', 31, '남', '010-7777-1234', '강원 춘천', 'LV', 900000000,'','');
insert into department values(2, '아이유', 30, '여', '010-0516-1234', '서울 서초', 'GUCCI', 1500000000,'','');
insert into department values(3, '박지성', 31, '남', '010-7775-1235', '강원 춘천', 'LV', 900000000,'','');
insert into department values(4, '박세리', 30, '여', '010-0516-1234', '서울 서초', 'GUCCI', 1500000000,'','');
insert into department values(5, '임영웅', 30, '남', '010-0517-1235', '서울 역삼', 'ROLEX', 150000000,'','');

DELETE mart
WHERE custid = 1;


-- Task2_0520. Customer 테이블에서 박세리 고객의 주소를 김연아 고객의 주소로 변경하시오.
UPDATE CUSTOMER SET ADDRESS=(SELECT ADDRESS FROM CUSTOMER WHERE NAME='김연아') WHERE NAME='박세리';
SELECT * FROM CUSTOMER;
-- 원래대로 복구
UPDATE CUSTOMER SET ADDRESS='대한민국 대전' WHERE NAME='박세리';

-- Task3_0520.도서 제목에 ‘야구’가 포함된 도서를 ‘농구’로 변경한 후 도서 목록, 가격을 보이시오.
UPDATE BOOK SET BOOKNAME=REPLACE(BOOKNAME,'야구','농구');
SELECT * FROM BOOK;

---- DATA가 실재로 바뀌지는 않고 검색 시에 변경만 되서.. TABLE의 값은 원래대로..
SELECT BOOKID, REPLACE(BOOKNAME,'야구','농구') BOOKNAME, PUBLISHER, PRICE
FROM BOOK;

-- 원래대로 복구
UPDATE BOOK SET BOOKNAME=REPLACE(BOOKNAME,'농구','야구');

-- Task4_0520. 마당서점의 고객 중에서 같은 성(姓)을 가진 사람이 몇 명이나 되는지 성별 인원수를 구하시오.
-- SUBSTR(원본문자열 혹은 컬럼, 시작위치, 추출개수)
SELECT 성, COUNT(성) FROM (SELECT SUBSTR(NAME, 1, 1) as 성 FROM CUSTOMER)
GROUP BY 성
ORDER BY 성;
-- 강사님
SELECT SUBSTR(NAME, 1, 1) 성, COUNT(*) 인원 
FROM CUSTOMER
GROUP BY SUBSTR(NAME, 1, 1)
ORDER BY SUBSTR(NAME, 1, 1);

-- Task5_0520. 마당서점은 주문일로부터 10일 후 매출을 확정한다. 각 주문의 확정일자를 구하시오.
SELECT ORDERDATE AS "주문 일자", TO_DATE(ORDERDATE,'yyyy-mm-dd') + 10 AS "확정 일자" FROM ORDERS;

-- 강사님
SELECT ORDERDATE "주문 일자", ORDERDATE + 10 "확정 일자" FROM ORDERS;

-- Q. 마당서점은 주문일로부터 2개월 후 매출을 확정한다. 각 주문의 확정일자를 구하시오.
SELECT ORDERDATE "주문 일자", add_months(ORDERDATE, 2) "확정 일자" FROM ORDERS;

-- Task6_0520.마당서점이 2020년 7월 7일에 주문받은 도서의 주문번호, 주문일, 고객번호, 도서번호를 모두 보이시오. 
-- 단 주문일은 ‘yyyy-mm-dd 요일’ 형태로 표시한다.
SELECT ORDERID, TO_CHAR(ORDERDATE, 'yyyy-mm-dd-DAY') AS "주문일", CUSTID, BOOKID
FROM ORDERS
WHERE ORDERDATE = '2020-07-07';
-- WHERE ORDERDATE = TO_DATE('2020-07-07', 'YYYY-MM-DD');
-- WHERE ORDERDATE = TO_DATE('07/07/24', 'DD/MM/YY');

-- ALL PRINT
SELECT ORDERID, ORDERDATE, CUSTID, BOOKID, TO_CHAR(ORDERDATE, 'day'), TO_CHAR(ORDERDATE, 'yyyy-mm-dd DAY')
FROM ORDERS
WHERE ORDERDATE = '2020-07-07';

SELECT ORDERID, ORDERDATE, CUSTID, BOOKID, TO_CHAR(ORDERDATE, 'day'), TO_DATE(ORDERDATE, 'yyyy-mm-dd')
FROM ORDERS
WHERE ORDERDATE = '2020-07-07';

-- Task7_0520. 평균 주문금액 이하의 주문에 대해서 주문번호와 금액을 보이시오.
SELECT ORDERID, SALEPRICE 
FROM ORDERS
WHERE SALEPRICE < (SELECT AVG(SALEPRICE)
FROM ORDERS);

SELECT O1.ORDERID, O1.SALEPRICE 
FROM ORDERS O1
WHERE O1.SALEPRICE < (SELECT AVG(O2.SALEPRICE)
FROM ORDERS O2);


-- 서브 쿼리를 O2별칭으로 지정, 서브 쿼리인 SALEPRICE의 평균 값을 AVG_SALEPRICE로 계산해서 O2로
SELECT O1.ORDERID, O1.SALEPRICE 
FROM ORDERS O1
JOIN (SELECT AVG(SALEPRICE) AS AVG_SALEPRICE FROM ORDERS) O2
ON O1.SALEPRICE < O2.AVG_SALEPRICE;

-- Task8_0520. 대한민국’에 거주하는 고객에게 판매한 도서의 총 판매액을 구하시오.
-- USING WHERE
SELECT SUM(O.SALEPRICE) AS "총판매액"
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID=C.CUSTID
AND C.ADDRESS LIKE '%대한민국%';

-- USING JOIN
SELECT SUM(O.SALEPRICE) AS "총판매액"
FROM ORDERS O
INNER JOIN CUSTOMER C ON O.CUSTID=C.CUSTID
WHERE C.ADDRESS LIKE '%대한민국%';

-- USING SUB-QUERY
SELECT SUM(SALEPRICE) AS "총판매액"
FROM ORDERS
WHERE CUSTID IN (SELECT CUSTID FROM CUSTOMER WHERE ADDRESS LIKE '%대한민국%');

---- 대한민국 외 거주하는...
SELECT SUM(O.SALEPRICE) AS "총판매액"
FROM ORDERS O, CUSTOMER C
WHERE O.CUSTID=C.CUSTID
AND C.ADDRESS NOT LIKE '%대한민국%';

-----------------------------------------------------------------------------------------
-- 단순 계산 할 때 DUMMY로 DUAL을 쓴다.
-- 절대값
SELECT ABS(-78), ABS(+78) FROM DUAL;
-- 반올림
SELECT ROUND(4.897,1) FROM DUAL;

-- Q. 고객별 평균 주문 금액을 백원 단위로 반올림한 값을 구하시오
SELECT * FROM ORDERS;
SELECT CUSTID AS 고객번호, ROUND(AVG(SALEPRICE), -2) AS "평균 주문 금액"
FROM ORDERS
GROUP BY CUSTID;

-- Q. 굿스포츠에서 출판한 도서의 제목과 제목의 글자수 바이트 수를 보이시오
SELECT BOOKNAME 제목, LENGTH(BOOKNAME) 글자수, LENGTHB(BOOKNAME) 바이트수
FROM BOOK
WHERE PUBLISHER = '굿스포츠';


-------------------------------------- SYSTEM 시간 DATE 가져오기
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS DAY') SYSDATE1
FROM DUAL;

-------------------------------------- DEFAULT 정의하기
SELECT NAME 이름, nvl(PHONE, '연락처 없음') 전화번호
FROM CUSTOMER;


-------------------------------------- 앞의 몇가지 케이스에 대해서만 검색하기  ==> 가상의 ROWNUM
SELECT ROWNUM 순번,  CUSTID 고객번호, NAME 이름,  PHONE 전화번호
FROM CUSTOMER
WHERE ROWNUM < 3;


-- 실습 2인 1조 
-- 학교 관리를 위하여 테이블 2개 이상 DB로 구축하고 3개 이상 활용할 수 있는 CASE를 만드세요
-- 출결 관리, 학적관리, 성적 관리

DROP TABLE TEACHERS cascade constraints purge;
CREATE TABLE TEACHERS(
    NAME VARCHAR2(20), -- 이름
    BIRTH DATE, -- 생일
    AGE NUMBER, -- 나이
    SX VARCHAR2(10),    --  성별
    PHONE VARCHAR2(15), --  핸드폰번호
    ADDRESS VARCHAR2(50), -- 주소
    SUBJECT VARCHAR2(10), -- 담당 과목
    CLASS_ASSIGNED VARCHAR2(15), -- 담당 반
    PRIMARY KEY (CLASS_ASSIGNED)
);


DROP TABLE STUDENTS cascade constraints purge;
CREATE TABLE STUDENTS(
    NAME VARCHAR2(20), -- 학생명
    STDID NUMBER(10), -- 학생 번호
    BIRTH DATE, -- 학생 생리
    AGE NUMBER, -- 나이
    SX VARCHAR2(10), -- 성별
    PHONE VARCHAR2(15), -- 핸드폰 번호
    ADDRESS VARCHAR2(50), -- 주소
    FAV_JUBJECT VARCHAR2(10), -- 과목
    CLASS   VARCHAR2(15), -- 반
    FOREIGN KEY (CLASS) REFERENCES TEACHERS(CLASS_ASSIGNED) ON DELETE CASCADE
);

INSERT INTO TEACHERS VALUES ('김영희', '1993-02-03', 29, '여', '010-1234-5678', '서울 강남', '영어', '2학년 3반');
INSERT INTO TEACHERS VALUES ('이철수', '1987-12-15', 34, '남', '010-9876-5432', '부산 해운대', '과학', '1학년 2반');
INSERT INTO TEACHERS VALUES ('박민수', '1990-08-20', 31, '남', '010-1234-5678', '서울 서초', '수학', '3학년 1반');
INSERT INTO TEACHERS VALUES ('정지은', '1985-06-10', 36, '여', '010-5678-1234', '인천 남구', '국어', '2학년 2반');
INSERT INTO TEACHERS VALUES ('홍길동', '1991-03-25', 30, '남', '010-9876-5432', '대전 동구', '역사', '1학년 3반');
INSERT INTO TEACHERS VALUES ('이영수', '1988-11-15', 33, '남', '010-3456-7890', '대구 수성', '체육', '3학년 4반');
INSERT INTO TEACHERS VALUES ('김미영', '1994-09-18', 27, '여', '010-5678-1234', '광주 서구', '미술', '2학년 1반');
INSERT INTO TEACHERS VALUES ('박승호', '1982-07-20', 39, '남', '010-2345-6789', '경기 안양', '음악', '1학년 12반');
INSERT INTO TEACHERS VALUES ('정다영', '1993-05-30', 28, '여', '010-7890-1234', '경북 포항', '한국사', '3학년 3반');
INSERT INTO TEACHERS VALUES ('이지현', '1997-04-08', 24, '여', '010-1234-5678', '경남 창원', '영어', '2학년 17반');
INSERT INTO TEACHERS VALUES ('김철호', '1981-08-10', 40, '남', '010-3456-7890', '전남 목포', '과학', '1학년 1반');
INSERT INTO TEACHERS VALUES ('박지은', '1989-10-05', 32, '여', '010-5678-1234', '서울 강서', '수학', '3학년 2반');
INSERT INTO TEACHERS VALUES ('정승민', '1996-01-12', 25, '남', '010-2345-6789', '인천 연수', '국어', '1학년 5반');
INSERT INTO TEACHERS VALUES ('김민지', '1987-07-22', 34, '여', '010-7890-1234', '경기 고양', '역사', '2학년 4반');
INSERT INTO TEACHERS VALUES ('이영호', '1992-12-14', 29, '남', '010-1234-5678', '대전 중구', '체육', '1학년 4반');
INSERT INTO TEACHERS VALUES ('최현우', '1986-04-30', 35, '남', '010-3456-7890', '광주 동구', '미술', '3학년 19반');
INSERT INTO TEACHERS VALUES ('이가연', '1998-11-05', 23, '여', '010-5678-1234', '부산 사하', '음악', '2학년 8반');
INSERT INTO TEACHERS VALUES ('김동호', '1990-02-28', 31, '남', '010-2345-6789', '경북 경주', '한국사', '3학년 17반');
INSERT INTO TEACHERS VALUES ('장지은', '1983-09-15', 38, '여', '010-7890-1234', '전북 전주', '영어', '1학년 16반');
INSERT INTO TEACHERS VALUES ('정준우', '1995-05-18', 26, '남', '010-1234-5678', '경기 수원', '과학', '2학년 20반');
INSERT INTO TEACHERS VALUES ('이지민', '1980-12-10', 41, '여', '010-3456-7890', '서울 강남', '수학', '3학년 8반');
INSERT INTO TEACHERS VALUES ('최다영', '1988-07-20', 33, '여', '010-9876-5432', '부산 해운대', '국어', '1학년 9반');
INSERT INTO TEACHERS VALUES ('김성호', '1993-04-03', 28, '남', '010-2345-6789', '인천 남구', '역사', '2학년 19반');
INSERT INTO TEACHERS VALUES ('박미영', '1997-01-28', 24, '여', '010-7890-1234', '대구 수성', '체육', '1학년 6반');
INSERT INTO TEACHERS VALUES ('김승호', '1981-10-08', 40, '남', '010-1234-5678', '서울 강서', '미술', '2학년 10반');
INSERT INTO TEACHERS VALUES ('이지은', '1994-09-03', 27, '여', '010-3456-7890', '대전 동구', '음악', '1학년 17반');
INSERT INTO TEACHERS VALUES ('최지우', '1985-03-20', 36, '남', '010-5678-1234', '경기 안양', '한국사', '3학년 20반');
INSERT INTO TEACHERS VALUES ('박영수', '1998-11-22', 23, '남', '010-2345-6789', '경북 포항', '영어', '2학년 9반');
INSERT INTO TEACHERS VALUES ('김민수', '1991-06-07', 30, '여', '010-7890-1234', '전남 목포', '과학', '1학년 10반');

SELECT * FROM TEACHERS;


INSERT INTO STUDENTS VALUES ('김철수', 220634, '2006-03-15', 17, '남', '010-1234-5678', '서울 강남', '영어', '3학년 3반');
INSERT INTO STUDENTS VALUES ('이영희', 230223, '2007-04-20', 15, '여', '010-9876-5432', '부산 해운대', '과학', '2학년 2반');
INSERT INTO STUDENTS VALUES ('박민지', 240312, '2008-06-23', 14, '여', '010-2345-6789', '대구 수성', '수학', '1학년 1반');
INSERT INTO STUDENTS VALUES ('정성호', 250506, '2007-09-08', 15, '남', '010-8765-4321', '인천 남구', '국어', '2학년 1반');
INSERT INTO STUDENTS VALUES ('이수진', 260721, '2006-12-30', 16, '여', '010-3456-7890', '광주 동구', '역사', '3학년 4반');
INSERT INTO STUDENTS VALUES ('김태영', 270830, '2005-11-10', 17, '남', '010-7890-1234', '서울 송파', '음악', '1학년 3반');
INSERT INTO STUDENTS VALUES ('박현수', 280917, '2006-01-20', 16, '남', '010-4567-8901', '대전 중구', '미술', '2학년 2반');
INSERT INTO STUDENTS VALUES ('정지은', 290102, '2007-03-05', 15, '여', '010-2345-6789', '경기 수원', '체육', '3학년 1반');
INSERT INTO STUDENTS VALUES ('김승호', 300206, '2006-11-18', 16, '남', '010-7890-1234', '서울 강동', '한국사', '1학년 2반');
INSERT INTO STUDENTS VALUES ('이수진', 310301, '2008-04-30', 14, '여', '010-3456-7890', '경북 포항', '미술', '2학년 3반');
INSERT INTO STUDENTS VALUES ('박영민', 320413, '2005-06-15', 17, '남', '010-9876-5432', '전남 목포', '음악', '3학년 4반');
INSERT INTO STUDENTS VALUES ('정다영', 330520, '2006-07-20', 16, '여', '010-2345-6789', '서울 마포', '체육', '1학년 1반');
INSERT INTO STUDENTS VALUES ('이재현', 340606, '2005-03-04', 17, '남', '010-7890-1234', '경남 창원', '미술', '2학년 4반');
INSERT INTO STUDENTS VALUES ('김지현', 350707, '2008-01-20', 14, '여', '010-3456-7890', '서울 서초', '수학', '3학년 1반');
INSERT INTO STUDENTS VALUES ('최승호', 360822, '2006-09-18', 16, '남', '010-1234-5678', '부산 사하', '국어', '1학년 4반');
INSERT INTO STUDENTS VALUES ('박수민', 370925, '2007-05-22', 15, '여', '010-9876-5432', '경기 안양', '과학', '2학년 1반');
INSERT INTO STUDENTS VALUES ('김영호', 380107, '2005-08-07', 17, '남', '010-2345-6789', '대전 서구', '한국사', '3학년 2반');
INSERT INTO STUDENTS VALUES ('이현주', 390215, '2006-04-15', 16, '여', '010-3456-7890', '서울 강서', '체육', '1학년 3반');
INSERT INTO STUDENTS VALUES ('정재원', 400330, '2007-06-28', 15, '남', '010-1234-5678', '인천 부평', '영어', '2학년 1반');
INSERT INTO STUDENTS VALUES ('최지훈', 410406, '2005-02-09', 17, '남', '010-9876-5432', '경북 경주', '수학', '3학년 2반');
INSERT INTO STUDENTS VALUES ('김지영', 420502, '2008-01-19', 14, '여', '010-2345-6789', '대구 달서', '미술', '1학년 1반');
INSERT INTO STUDENTS VALUES ('이민재', 430603, '2006-06-12', 16, '남', '010-3456-7890', '서울 송파', '국어', '2학년 3반');
INSERT INTO STUDENTS VALUES ('박수진', 440727, '2005-12-03', 16, '여', '010-1234-5678', '경기 고양', '역사', '3학년 1반');
INSERT INTO STUDENTS VALUES ('정지원', 450817, '2008-06-28', 14, '남', '010-9876-5432', '전북 전주', '체육', '1학년 1반');
INSERT INTO STUDENTS VALUES ('김은지', 460920, '2007-11-18', 15, '여', '010-2345-6789', '광주 북구', '음악', '2학년 2반');
INSERT INTO STUDENTS VALUES ('최준호', 470002, '2006-09-07', 16, '남', '010-3456-7890', '경남 진주', '과학', '3학년 1반');
INSERT INTO STUDENTS VALUES ('이가영', 480106, '2005-08-23', 17, '여', '010-1234-5678', '서울 강북', '수학', '1학년 2반');
INSERT INTO STUDENTS VALUES ('박진우', 490225, '2008-04-12', 14, '남', '010-9876-5432', '인천 연수', '국어', '2학년 3반');
INSERT INTO STUDENTS VALUES ('정미영', 500312, '2007-11-05', 15, '여', '010-1234-5678', '서울 동작', '미술', '1학년 4반');
INSERT INTO STUDENTS VALUES ('김철수', 510406, '2004-03-15', 18, '남', '010-1234-5678', '서울 강남', '영어', '3학년 2반');
INSERT INTO STUDENTS VALUES ('이영희', 520423, '2005-04-20', 17, '여', '010-9876-5432', '부산 해운대', '과학', '2학년 2반');
INSERT INTO STUDENTS VALUES ('박민지', 530523, '2004-06-23', 17, '여', '010-2345-6789', '대구 수성', '수학', '1학년 1반');
INSERT INTO STUDENTS VALUES ('정성호', 540606, '2003-09-08', 18, '남', '010-8765-4321', '인천 남구', '국어', '2학년 1반');
INSERT INTO STUDENTS VALUES ('이수진', 550721, '2004-12-30', 17, '여', '010-3456-7890', '광주 동구', '역사', '3학년 2반');
INSERT INTO STUDENTS VALUES ('김태영', 560830, '2003-11-10', 18, '남', '010-7890-1234', '서울 송파', '음악', '1학년 3반');
INSERT INTO STUDENTS VALUES ('박현수', 570917, '2004-01-20', 18, '남', '010-4567-8901', '대전 중구', '미술', '2학년 2반');
INSERT INTO STUDENTS VALUES ('정지은', 580102, '2005-03-05', 17, '여', '010-2345-6789', '경기 수원', '체육', '3학년 2반');
INSERT INTO STUDENTS VALUES ('김승호', 590206, '2004-11-18', 17, '남', '010-7890-1234', '서울 강동', '한국사', '1학년 1반');
INSERT INTO STUDENTS VALUES ('이수진', 600301, '2006-04-30', 16, '여', '010-3456-7890', '경북 포항', '미술', '2학년 3반');
INSERT INTO STUDENTS VALUES ('박영민', 610413, '2003-06-15', 18, '남', '010-9876-5432', '전남 목포', '음악', '3학년 2반');
INSERT INTO STUDENTS VALUES ('정다영', 620520, '2004-07-20', 17, '여', '010-2345-6789', '서울 마포', '체육', '1학년 1반');
INSERT INTO STUDENTS VALUES ('이재현', 630606, '2003-03-04', 18, '남', '010-7890-1234', '경남 창원', '미술', '2학년 2반');
INSERT INTO STUDENTS VALUES ('김지현', 640707, '2006-01-20', 16, '여', '010-3456-7890', '서울 서초', '수학', '3학년 3반');

SELECT * FROM STUDENTS;


DROP TABLE SCOREBOARD cascade constraints purge;
CREATE TABLE SCOREBOARD(
    NAME VARCHAR2(20),
    STDID NUMBER(10),
    MATH1 NUMBER(10),
    MATH2 NUMBER(10),
    MATH3 NUMBER(10),
    SCORE_MATH VARCHAR2(10),
    PHYS1 NUMBER(10),
    PHYS2 NUMBER(10),
    PHYS3 NUMBER(10),
    SCORE_PHYS VARCHAR2(10),
    ABSENCE NUMBER(10),
    FLUNK VARCHAR2(10)
);

INSERT	INTO	SCOREBOARD	VALUES	('김철수',220634,74,84,56,NULL,63,78,89,NULL,1,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이영희',230223,30,30,78,NULL,40,64,52,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박민지',240312,46,33,38,NULL,62,29,31,NULL,1,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정성호',250506,80,35,47,NULL,70,64,97,NULL,0,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이수진',260721,96,63,96,NULL,56,40,61,NULL,1,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김태영',270830,81,73,33,NULL,61,51,44,NULL,7,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박현수',280917,91,58,69,NULL,59,40,85,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정지은',290102,83,64,63,NULL,63,96,69,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김승호',300206,89,32,78,NULL,80,53,39,NULL,2,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이수진',310301,37,63,63,NULL,67,27,68,NULL,4,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박영민',320413,31,27,58,NULL,43,80,51,NULL,3,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정다영',330520,73,89,26,NULL,99,79,70,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이재현',340606,26,61,62,NULL,40,31,86,NULL,10,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김지현',350707,84,38,58,NULL,54,51,48,NULL,4,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('최승호',360822,52,55,45,NULL,24,73,62,NULL,10,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박수민',370925,47,68,44,NULL,72,48,69,NULL,4,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김영호',380107,56,69,90,NULL,98,49,88,NULL,4,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이현주',390215,20,41,49,NULL,56,32,26,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정재원',400330,43,21,79,NULL,39,52,24,NULL,2,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('최지훈',410406,56,83,26,NULL,71,75,52,NULL,6,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김지영',420502,83,83,71,NULL,38,98,44,NULL,2,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이민재',430603,40,77,27,NULL,94,77,73,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박수진',440727,39,62,48,NULL,74,83,94,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정지원',450817,91,82,91,NULL,37,45,20,NULL,1,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김은지',460920,86,22,66,NULL,91,28,79,NULL,0,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('최준호',470002,50,23,40,NULL,62,41,49,NULL,3,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이가영',480106,58,32,43,NULL,58,43,66,NULL,2,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박진우',490225,27,94,53,NULL,33,36,44,NULL,3,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정미영',500312,69,78,21,NULL,48,23,61,NULL,5,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김철수',510406,31,88,99,NULL,54,21,95,NULL,7,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이영희',520423,30,47,27,NULL,57,84,58,NULL,6,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박민지',530523,24,33,37,NULL,41,68,57,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정성호',540606,66,41,48,NULL,48,50,25,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이수진',550721,64,86,49,NULL,93,70,67,NULL,1,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김태영',560830,92,95,56,NULL,23,48,39,NULL,0,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박현수',570917,64,94,27,NULL,53,92,33,NULL,0,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정지은',580102,73,83,33,NULL,97,98,58,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김승호',590206,67,40,92,NULL,71,93,61,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이수진',600301,78,41,57,NULL,21,92,22,NULL,2,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('박영민',610413,75,51,84,NULL,54,76,26,NULL,8,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('정다영',620520,55,33,53,NULL,81,53,51,NULL,9,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('이재현',630606,82,41,25,NULL,40,45,81,NULL,6,NULL);
INSERT	INTO	SCOREBOARD	VALUES	('김지현',640707,30,57,72,NULL,54,32,96,NULL,6,NULL);

DROP TABLE RELOCATEE cascade constraints purge;
-- 교육부 전근자 명단 테이블 생성
CREATE TABLE RELOCATEE(
    NAME VARCHAR2(20),      -- 전근자 이름
    RELO_DATE DATE          -- 전근 일자
);

INSERT	INTO	RELOCATEE	VALUES	('김철호', TO_DATE('2024-07-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('박준혁', TO_DATE('2024-07-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('김지현', TO_DATE('2024-07-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('김소연', TO_DATE('2024-07-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('이지훈', TO_DATE('2024-08-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('박승우', TO_DATE('2024-08-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('최민지', TO_DATE('2024-08-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('윤하은', TO_DATE('2024-08-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('이민준', TO_DATE('2024-09-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('장지우', TO_DATE('2024-09-01','YYYY-MM-DD'));
INSERT	INTO	RELOCATEE	VALUES	('최성민', TO_DATE('2024-09-01','YYYY-MM-DD'));

SELECT * FROM RELOCATEE;
    
SELECT * FROM TEACHERS;
SELECT * FROM STUDENTS;
SELECT * FROM SCOREBOARD;
SELECT * FROM RELOCATEE;

------------------------------ Q.분반 별로 소속된 학생들과 담당 선생님을 검색
SELECT S.STDID 학번, S.NAME 이름, S.CLASS "학년/반", T.NAME "담임선생님"
FROM STUDENTS S 
INNER JOIN TEACHERS T ON S.CLASS = T.CLASS_ASSIGNED
ORDER BY "학년/반";


------------------------------ Q.성적 TABLE에서 수학/물리 각각의 과목에서 1차, 2차, 3차, 시험에 대해 가중치 X 0.3을 적용한 시험
------------------------------ 합산 점수에 결석일수를 감해서 최종 수학/물리 과목 점수를 SCORE_MATH와 SCORE_PHYS COLUMN에 UPDATE
UPDATE SCOREBOARD SET
SCORE_MATH = ROUND((MATH1 * 0.3 + MATH2 * 0.3 + MATH3 * 0.3) - ABSENCE),
SCORE_PHYS = ROUND((PHYS1 * 0.3 + PHYS2 * 0.3 + PHYS3 * 0.3) - ABSENCE);
SELECT * FROM SCOREBOARD;



------------------------------ Q. 수학 물리 과목 모두 1,2,3차 시험과 출결점수로 산출된 합산 점수로부터 
------------------------------ 65점 이상: A, 64~55점: B, 54~45점 : C, 44~36점 D, 35점 이하: F 학점으로 성적 처리해서 
------------------------------ GRADE_MATH와 GRADE_PHYS NEW COLUMN 으로 검색 쿼리
SELECT NAME, STDID, SCORE_MATH,
CASE
WHEN SCORE_MATH >= 65 THEN 'A'
WHEN SCORE_MATH BETWEEN 55 AND 64 THEN 'B'
WHEN SCORE_MATH BETWEEN 45 AND 54 THEN 'C'
WHEN SCORE_MATH BETWEEN 36 AND 44 THEN 'D'
ELSE 'F'
END AS GRADE_MATH,
SCORE_PHYS,
CASE
WHEN SCORE_PHYS >= 65 THEN 'A'
WHEN SCORE_PHYS BETWEEN 55 AND 64 THEN 'B'
WHEN SCORE_PHYS BETWEEN 45 AND 54 THEN 'C'
WHEN SCORE_PHYS BETWEEN 36 AND 44 THEN 'D'
ELSE 'F'
END AS GRADE_PHYS,
ABSENCE,
FLUNK
FROM SCOREBOARD;

------------------------------ Q.위와 같은 로직에 따라 수학과 물리의 점수를 그래이딩 하고, 각 과목의 낙제자를 검색해서 FLUNK 컬럼 UPDATE
UPDATE SCOREBOARD
SET FLUNK = CASE
WHEN TO_NUMBER(SCORE_MATH) <= 35 AND TO_NUMBER(SCORE_PHYS) <= 35 THEN '유급'
WHEN TO_NUMBER(SCORE_MATH) <= 35 OR TO_NUMBER(SCORE_PHYS) <= 35 THEN '경고'
ELSE 'PASS'
END;
SELECT * FROM SCOREBOARD;

------------------------------ Q.성적이 유급 혹은 잠정 보류에 해당하는 학생과 담임 선생님의 리스트를 쿼리
SELECT
    S.NAME AS 학생이름,
    S.CLASS AS "학년/반",
    T.NAME AS 담당교사,
    SB.FLUNK AS 유급여부
FROM SCOREBOARD SB
INNER JOIN STUDENTS S ON SB.STDID = S.STDID
INNER JOIN TEACHERS T ON S.CLASS = T.CLASS_ASSIGNED
WHERE SB.FLUNK IN ('보류', '유급');


------------------------------ Q.STUDENT TABLE에서 학생 명단에 학년을 추출해서 쿼리
SELECT
    NAME AS STUDENT_NAME,
    STDID AS STUDENT_ID,
    AGE AS STUDENT_AGE,
    SUBSTR(CLASS, 1, 1) AS GRADE
FROM STUDENTS
ORDER BY GRADE;


------------------------------ Q.두 과목 모두에서 낙제한 유급 학생과 담임 선생님의 명단 쿼리
SELECT
    S.NAME AS 학생이름,
    S.CLASS AS "학년/반",
    T.NAME AS "하위 고과 예정 교사"
FROM SCOREBOARD SB
INNER JOIN STUDENTS S ON SB.STDID = S.STDID
INNER JOIN TEACHERS T ON S.CLASS = T.CLASS_ASSIGNED
WHERE SB.FLUNK IN ('유급');

------------------------------ Q.반별 평균 점수가 가장 높은 반 순서로 정렬 (학년 구분 없이)
SELECT
    T.CLASS_ASSIGNED AS CLASS,
    ROUND(AVG(SB_MATH_SCORE),2) AS AVG_MATH_SCORE,
    T.NAME AS TEACHER_NAME
FROM TEACHERS T
JOIN STUDENTS S ON T.CLASS_ASSIGNED = S.CLASS
JOIN (SELECT STDID, AVG(TO_NUMBER(SCORE_MATH)) AS SB_MATH_SCORE
    FROM SCOREBOARD
    GROUP BY STDID) SB ON S.STDID = SB.STDID
GROUP BY T.CLASS_ASSIGNED, T.NAME
ORDER BY AVG_MATH_SCORE DESC, T.CLASS_ASSIGNED;
--------------------------------------------------- Q.반별 평균 점수가 가장 높은 반 순서로 정렬 (1학년 만)
SELECT
    T.CLASS_ASSIGNED AS CLASS,
    ROUND(AVG(SB_MATH_SCORE), 2) AS AVG_MATH_SCORE,
    T.NAME AS TEACHER_NAME
FROM TEACHERS T
JOIN STUDENTS S ON T.CLASS_ASSIGNED = S.CLASS
JOIN (SELECT STUDENTS.STDID,AVG(TO_NUMBER(SCORE_MATH)) AS SB_MATH_SCORE
    FROM SCOREBOARD
    JOIN STUDENTS ON SCOREBOARD.STDID = STUDENTS.STDID
    AND SUBSTR(STUDENTS.CLASS, 1, 1) = '1' 
    GROUP BY STUDENTS.STDID) SB ON S.STDID = SB.STDID
GROUP BY T.CLASS_ASSIGNED, T.NAME
ORDER BY AVG_MATH_SCORE DESC;

--------------------------------------------------- Q.반별 평균 점수가 가장 높은 반 순서로 정렬 (3학년 만)
SELECT
    T.CLASS_ASSIGNED AS CLASS,
    ROUND(AVG(SB_MATH_SCORE), 2) AS AVG_MATH_SCORE,
    T.NAME AS TEACHER_NAME
FROM TEACHERS T
JOIN STUDENTS S ON T.CLASS_ASSIGNED = S.CLASS
JOIN (SELECT STUDENTS.STDID,AVG(TO_NUMBER(SCORE_MATH)) AS SB_MATH_SCORE
    FROM SCOREBOARD
    JOIN STUDENTS ON SCOREBOARD.STDID = STUDENTS.STDID
    AND SUBSTR(STUDENTS.CLASS, 1, 1) = '3' 
    GROUP BY STUDENTS.STDID) SB ON S.STDID = SB.STDID
GROUP BY T.CLASS_ASSIGNED, T.NAME
ORDER BY AVG_MATH_SCORE DESC;

--------------------------------------------------- Q. 학년 별 학생 수와 선생님 수, 선생님 한 명당 학생 수 비율이 높은 순으로 정리
WITH StudentCount AS (
    SELECT SUBSTR(CLASS, 1, 1) AS GRADE, COUNT(*) AS NUM_STUDENTS
    FROM STUDENTS
    GROUP BY SUBSTR(CLASS, 1, 1)),
TeacherCount AS ( 
    SELECT SUBSTR(CLASS_ASSIGNED, 1, 1) AS GRADE, COUNT(*) AS NUM_TEACHERS
    FROM TEACHERS 
    GROUP BY SUBSTR(CLASS_ASSIGNED, 1, 1)),
StudentPerTeacher AS (
    SELECT S.GRADE, S.NUM_STUDENTS AS STUDENT_COUNT, T.NUM_TEACHERS AS TEACHER_COUNT,
        ROUND(S.NUM_STUDENTS / T.NUM_TEACHERS, 2) AS STUDENT_PER_TEACHER
    FROM StudentCount S
    JOIN TeacherCount T ON S.GRADE = T.GRADE)
SELECT SPT.GRADE, SPT.STUDENT_COUNT, SPT.TEACHER_COUNT, SPT.STUDENT_PER_TEACHER
FROM StudentPerTeacher SPT
ORDER BY
    SPT.STUDENT_PER_TEACHER DESC;


--------------------------------------------------- Q. 전근갈 교사의 학생들을 가장 학생이 적은 반으로 배정
UPDATE STUDENTS
SET CLASS = (SELECT  C.CLASS
            FROM (SELECT B.CLASS, COUNT(B.CLASS) AS CNT
                  FROM TEACHERS A, STUDENTS B
                  WHERE A.CLASS_ASSIGNED = B.CLASS AND B.CLASS LIKE '1%' AND A.NAME != '김철호'
                  GROUP BY B.CLASS
                  ORDER BY COUNT(B.CLASS), CLASS) C
            WHERE ROWNUM = 1)
WHERE CLASS = (SELECT CLASS_ASSIGNED
            FROM TEACHERS
            WHERE NAME = '김철호');


ROLLBACK;
DELETE FROM teachers WHERE name = '김철호';




