SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM IMPORTED_BOOK;
SELECT * FROM ORDERS;
SELECT PRICE, BOOKID FROM BOOK;
SELECT NAME,address, PHONE FROM CUSTOMER;


-- 중복 없이 출력 DISTINCT
SELECT PUBLISHER FROM BOOK;
SELECT DISTINCT PUBLISHER FROM BOOK;           

--Q. 가격이 10,000이상인 도서를 검색
-- 조건 검색해서 SELECT는 "WHERE"
SELECT * FROM BOOK 
WHERE  PRICE > 20000;

-- 가격이 10000이상 20000이하인 도서를 검색하시오 (2가지 방법)
-- OPTION1
SELECT * FROM BOOK 
WHERE  PRICE >= 10000 AND PRICE <= 20000;
-- OPTION2
SELECT * FROM BOOK 
WHERE PRICE BETWEEN 10000 AND 20000;

-- LIKE는 정확히 '축구의 역사'와 일치하는 행만 선택: LIKE
SELECT BOOKNAME, PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '축구의 역사';

-- '축구'가 포함된 출판사: '%xx%'
SELECT BOOKNAME, PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '%축구%';

-- 도서이름의 왼쪽 두 번째 위치에 '구'라는 문자열을 갖는 도서: '_X%'
SELECT BOOKNAME ,PUBLISHER FROM BOOK
WHERE BOOKNAME LIKE '_구%';


-- 정렬 오름차순 ORDERED BY
SELECT * FROM BOOK
ORDER BY BOOKNAME;

-- 정렬 내림차순: DESC
SELECT * FROM BOOK
ORDER BY PRICE DESC;

-- Q. 도서를 가격순으로 검색하고, 가격이 같으면 이름순으로 검색
SELECT * FROM BOOK
ORDER BY PRICE, BOOKNAME;

-- Q. 2번 김연아 고객이 주문한 도서의 총 판매액을 구하시오
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
-- 조인이 필요해서 지금은 x

-- (STEP1) 일단 김연아의 COSTID가 2이므로
SELECT SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE CUSTID = 2;

-- (STEP2) GROUP BY: 데이터를 특정 기준에 따라 그룹화하는데 사용. 이를 통해 집계 함수 (SUM, AVG, MAX, MIN, COUNT)를 이용
SELECT SUM(SALEPRICE) AS TOTAL,
AVG(SALEPRICE) AS AVERAGE,
MAX(SALEPRICE) AS MAXIMUM,
MIN(SALEPRICE) AS MINIMUM
FROM ORDERS;


SELECT * FROM ORDERS;

-- 총 판매액을 CUSTID를 기준으로 그룹화
-- 아래 코드의 설명; ORDERS 테이블로 부터 COL을 (1)CUSTID, (2) COUNT(*), (3) SUM(SALEPRICE)로 검색하는데..
-- 이때 BOOKID가 5초과인 조건으로 CUSTID 기준으로 검색
SELECT CUSTID, COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5
GROUP BY CUSTID;
-- <== 여기서 GROUP BY CUSTID가 없으면 ERROR가 나오는데, 이건 CUSTID가 검색 컬럼에 포함되어 있으니 수행하기 불가능


-- CF) 그럼 CUSTID를 검색 COL에서 제거를 하고 "GROUP BY CUSTID"를 안하면 ERORR가 발생 안하나? ==> 에러 없음
SELECT COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5;

-- 도서 수량이 2보다 조건
SELECT CUSTID, COUNT(*) AS 도서수량, SUM(SALEPRICE) AS "총 판매액"
FROM ORDERS
WHERE BOOKID > 5
GROUP BY CUSTID
HAVING COUNT(*) > 2;

